---
title: "TDM - UTA Bus Speed Comparison Tool"
output: html_document
date: '2022-08-16'
runtime: shiny
resource_files:
- _targets.R
- _targets/objects/uta_map_points
- _targets/objects/tdm_uta_conversion
- _targets/objects/pk_0_estimated_speeds
- _targets/objects/ok_0_estimated_speeds
- _targets/objects/ok_1_estimated_speeds
- _targets/objects/pk_1_estimated_speeds
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(shinydashboard)
library(targets)
library(tarchetypes)
library(tidyverse)
library(sf)
library(leaflet)
library(mapview)
```


```{r,echo=FALSE}
tdm_uta_conversion <- tar_read(tdm_uta_conversion)
pk_0_estimated_speeds <- tar_read(pk_0_estimated_speeds)
ok_0_estimated_speeds <- tar_read(ok_0_estimated_speeds)
pk_1_estimated_speeds <- tar_read(pk_1_estimated_speeds)
ok_1_estimated_speeds <- tar_read(ok_1_estimated_speeds)
pk_estimated_speeds <- tar_read(pk_estimated_speeds)
ok_estimated_speeds <- tar_read(ok_estimated_speeds)
uta_points <- tar_read(uta_map_points)
```


```{r eruptions, echo=FALSE}
inputPanel(
  selectInput("Period", label = h3("Select Period"), 
    choices = list("Peak" = 1, "Off-Peak" = 2), 
    selected = 1),
  selectInput("Dir", label = h3("Select Direction"), 
    choices = list("1" = 1, "0" = 2, "Average" = 3), 
    selected = 1),
  numericInput("label", h3("Select Transit Line"), 11, min = 1, max = 109, step = 1)
)
```

```{r,echo = FALSE}
dlabel <- reactive({
  input$label
})
renderText({
  labelname <- tdm_uta_conversion %>% filter(LabelNum == dlabel())
  paste0("Transit Line: ", labelname$Label)
})
```

```{r, echo = FALSE}
#renderText({
#  "*Thickness of transit line based on speed ratio"
#})
```


```{r,echo = FALSE}
dperiod <- reactive({
  if(input$Period == 1 && input$Dir == 2){
    return(pk_0_estimated_speeds)
  }else {
    if(input$Period == 2 && input$Dir == 2){
      return(ok_0_estimated_speeds)
    }else {
      if(input$Period == 1 && input$Dir == 1){
        return(pk_1_estimated_speeds)
      }else{
        if(input$Period == 2 && input$Dir == 1){
          return(ok_1_estimated_speeds)
        }else{
          if(input$Period == 1 && input$Dir == 3){
            return(pk_estimated_speeds)
          }else{
            return(ok_estimated_speeds)
          }
        }
      }
    }
  }
})

finalPeriod <- reactive({
  if(input$Period == 1){"pk"}
  else{"ok"}
})
finalDir <- reactive({
  if(input$Dir == 1){return(c(1))}
  else{if(input$Dir == 2){return(c(0))}
      else{return(c(0,1))}}
})

renderLeaflet({
  routeMap <- dperiod() %>% 
    filter(LabelNum ==  dlabel()) %>% 
    st_as_sf %>% st_transform(4326)
  utaStops <- uta_points %>% 
    filter(PkOk == finalPeriod()) %>% 
    filter(DIR %in% finalDir()) %>% 
    filter(LabelNum == dlabel())
  
  leaflet() %>%
    addProviderTiles(providers$CartoDB.Positron) %>%
    addCircleMarkers(lng = utaStops$lon, lat = utaStops$lat,
      popup = paste("Avgmphdwell: ",utaStops$Avgmphdwell, "<br>",
                    "Avgmph: ",utaStops$Avgmph, "<br>",
                    "STOP1: ", utaStops$STOP, "<br>",
                    "STOP2: ", utaStops$STOP2),
      color = "red",
      radius = 8,
      group = "UTA Stops") %>%
    addPolylines(
      data = routeMap$geometry, 
      #weight = routeMap$speedRatio*10,
      group = "TDM Links",
      popup = paste("MODE:", routeMap$MODE, "<br>",
                  "ONEWAY:", routeMap$ONEWAY, "<br>",
                  "LINKSEQ1:", routeMap$LINKSEQ1, "<br>",
                  "LINKSEQ2:", routeMap$LINKSEQ2, "<br>",
                  "P_SPEED1:", routeMap$P_SPEED1, "<br>",
                  "P_SPEED2:", routeMap$P_SPEED2, "<br>",
                  "O_SPEED1:", routeMap$O_SPEED1, "<br>",
                  "O_SPEED2:", routeMap$O_SPEED2, "<br>",
                  "EstAvgmphdwell", routeMap$EstAvgmphdwell, "<br>",
                  "speedRatio:", routeMap$speedRatio)
    ) %>%
    addLayersControl(
          overlayGroups =c("TDM Links", "UTA Stops"),
          options = layersControlOptions(collapsed=FALSE)
          )
})

renderPlot({
  routeMap <- dperiod() %>% filter(LabelNum ==  dlabel()) %>% 
    st_as_sf %>% st_transform(4326) %>% as.tibble() %>%
    rename("Modeled" = ModelSpeed, "Observed" = EstAvgmphdwell) %>%
    mutate(Modeled = ifelse(is.na(Modeled),P_SPEED1,Modeled)) %>%
    select(LINKSEQ1,Observed,Modeled)  %>% 
    pivot_longer(!LINKSEQ1,names_to = "Type",values_to = "Speed")
  
    return(ggplot(routeMap, aes(x = LINKSEQ1, y = Speed, fill = Type))+
        geom_col(alpha = .25, position = "dodge2")+     
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
        geom_line(aes(x = LINKSEQ1,y = Speed, colour = Type))+
        scale_color_manual(values = c("blue","red")) +
        scale_fill_manual(values = c("blue","red")) +
        theme_bw()
      )

})

renderPlot({
  routeMap <- dperiod() %>% filter(LabelNum ==  dlabel()) %>% 
    st_as_sf %>% st_transform(4326) %>% as.tibble() %>%
    select(LINKSEQ1,PercentError) %>%
    mutate(col = ifelse(PercentError > 0, "blue","red"))
  
    return(ggplot(routeMap, aes(x = LINKSEQ1, y = PercentError, color = col))+
        geom_col(alpha = .25)+     
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
        scale_color_manual(values = c("lightblue","pink"))+
        theme(legend.position = "none") +
        theme_bw()
      )

})



```
