---
title: "UTA Bus Speeds using GTFS"
output: html_document
author: Chris Day
date: '2022-10-12'
---


```{r, include = FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(sf)
library(gtfstools)
#library(tidytransit)
library(gtfs2gps)
library(leaflet)
library(hms)
library(geotidy)
library(sfheaders)
```


```{r}
#read in gtfs data
gtfs_path <- "C:/Users/cday/Documents/projects/TDM-Bus-Speeds/data/UTA/gtfs.zip"
uta_gtfs <- gtfstools::read_gtfs(gtfs_path)
```

```{r}
#create data tables of gtfs data
trips <- uta_gtfs$trips
routes <- uta_gtfs$routes
stops_times <- uta_gtfs$stop_times
calendar_dates <- uta_gtfs$calendar_dates
```

```{r}
#calculate average speeds, times, etc.
uta_gps <- gtfs2gps(uta_gtfs, spatial_resolution = 100)
# Results:
#   356 out of 534 shapes (66.67%) were properly processed.
#   15818 out of 16234 trips (97.44%) were properly processed.

# create point and line datasets
uta_gps_points <- gps_as_sfpoints(uta_gps)
uta_gps_lines <- gps_as_sflinestring(uta_gps)
```

```{r}
# merge route name, dir, and other info onto geometry data
uta_gps_lines_arr <- uta_gps_lines %>% 
  left_join(trips, by = c("trip_id","shape_id")) %>%
  left_join(routes, by = c("route_id","route_type")) %>%
  # match route id with TDM/UTA route names
  group_by(trip_id) %>%
  arrange(trip_id,stop_sequence)

#' get timestamp data for each trip and route
#' determine peak and off peak times
uta_gps_lines_atr <- uta_gps_lines_arr %>%
  mutate(calcTime = ifelse(is.na(to_timestamp), NA, as_hms(difftime(lead(timestamp),timestamp)))) %>%
  mutate(cumtime2 = cumsum(calcTime)) %>%
  mutate(cumtime = ifelse(is.na(cumtime), cumtime2, cumtime)) %>%
  mutate(timepoint = ifelse(stop_sequence == 1, cumtime, cumtime - lag(cumtime)),
         startHour = as.numeric(substr(timestamp,1,2)),
         rownum = row_number()) %>%
  mutate(firstStartHour = ifelse(rownum == 1, startHour, NA)) %>%
  fill(firstStartHour, .direction = "down") %>%
  mutate(PkOk = ifelse(firstStartHour %in% c(6:8), "pk", ifelse(firstStartHour %in% c(9:14), "ok", "other")))
```

```{r}
mflines <- c("1004","12704","13304","210704","24904","128004","142204","340904","504","150804","4", "17")

uta_gps_lines_mf <- uta_gps_lines_atr %>%
  filter(service_id %in% mflines) %>%
  ungroup() %>%
  group_by(route_short_name, PkOk, direction_id, stop_sequence) %>%
  filter(PkOk != "other") %>%
  arrange(stop_sequence, from_timestamp)

uta_gps_lines_mf_sum <- uta_gps_lines_mf %>%
  group_by(route_short_name,PkOk,direction_id,stop_sequence) %>%
  summarize(aveTimepoint = mean(timepoint),
            aveDistance = mean(dist),
            aveSpeed = mean(speed))
```


```{r}
dir <- 0
route <- "11"
period <- "ok"
uta_gps_filtered <- uta_gps_lines_mf_sum %>%
  filter(route_short_name == route,
         PkOk == period,
         direction_id == dir)

leaflet(uta_gps_filtered) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolylines(
    data = uta_gps_filtered$geometry
  )
```



Break up Polylines into Individual Segments

```{r}
uta_gps_segments <- st_make_segments(uta_gps_lines_mf_sum)

uta_segments_test <- uta_gps_segments %>%
  filter(route_short_name == route,
         PkOk == period,
         direction_id == dir)

leaflet(uta_segments_test) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolylines(
    data = uta_segments_test$line
  )
```


Adding a Compass Direction to Each Segment

```{r}
uta_segments_geosphere <- uta_gps_segments %>%
  filter(!(is.na(lines)))
uta_segments_geosphere$orient = orient(uta_segments_geosphere)

uta_segments_compass_key <- uta_segments_geosphere %>%
  mutate(orient = ifelse(orient < 0, (360 + orient), orient)) %>%
  mutate(compass = ifelse(orient > 315 | orient <= 45, "NB",
                    ifelse(orient > 45 & orient <= 135, "EB",
                     ifelse(orient > 135 & orient <= 225, "SB",
                      ifelse(orient > 225 & orient <= 315, "WB", NA))))) %>% as_tibble() %>% select(-line) %>%
  select(uniquerow,orient,compass)

uta_segments_compass <- uta_gps_segments %>% as_tibble() %>%
  left_join(uta_segments_compass_key, by = c("uniquerow")) %>%
  st_as_sf() %>%
  filter(!is.na(aveSpeed))

leaflet(uta_segments_compass) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolylines(
    data = uta_segments_compass$line,
    popup = paste("DIR:", uta_segments_compass$compass, "<br>",
                  "uniquerow:", uta_segments_compass$uniquerow)
  )

```


Add Compass direction to TDM links


```{r}

```









Mega Loop to get every tdm centroid the attribute of the nearest GTFS segment (by direction, compass direction, route, and period)


















